### ISSUE TITLE
Can I run your pipeline without parent sample?

### ISSUE THREAD

**Issue by xiekunwhy** [YuSugihara/QTL-seq#1]
Hi,

Can I run your pipeline without parent sample? Or why parent is a necessary conditions?

Best wishes,
Kun

**Comment by YuSugihara** [comment]
Hi, 
sorry for my late response.

Parent sample is needed to polarize the allele frequencies around adjacent regions.
Currently, QTL-seq doesn't support the run without parent sample.
Maybe, you can try Fst statistics in population genetics to evaluate the difference between two populations.

Yu Sugihara
