### ISSUE TITLE
samtools error

### ISSUE THREAD

**Issue by Deeptirao** [YuSugihara/QTL-seq#11]
I have used your package earlier without any issues. But, I am getting this error even if I used the files I had used to successfully generate plots earlier. Please help soon.

[QTL-seq:2020-11-24 03:42:56] start to run QTL-seq.[QTL-seq:2020-11-24 03:42:56] maximum number of threads which you can use is up to 8.
[QTL-seq:2020-11-24 03:42:56] start to index reference fasta.
[QTL-seq:2020-11-24 03:49:38] indexing of reference successfully finished.
[QTL-seq:2020-11-24 03:49:38] start to filter reads.
[QTL-seq:2020-11-24 04:10:35] !!ERROR!! samtools view -b -f 147 -o new_qtlseq_yusugihara_output_F6vsF4/20_bam/bulk2.1000.f147.bam new_qtlseq_yusugihara_output_F6vsF4/20_bam/bulk2.1000.bam >> new_qtlseq_yusugihara_output_F6vsF4/log/samtools.bulk2.1000.f147.log 2>&1
[QTL-seq:2020-11-24 04:10:35] !!ERROR!! samtools view -b -f 83 -o new_qtlseq_yusugihara_output_F6vsF4/20_bam/bulk2.1000.f83.bam new_qtlseq_yusugihara_output_F6vsF4/20_bam/bulk2.1000.bam >> new_qtlseq_yusugihara_output_F6vsF4/log/samtools.bulk2.1000.f83.log 2>&1

**Comment by YuSugihara** [comment]
Sorry for my late response.

In some environments, SAMtools cannot be installed properly.
This is not the error of QTL-seq but the error of SAMtools in bioconda.

Probably, you can solve that problem by installing SAMtools by yourself.
