### ISSUE TITLE
SNP index calculation error

### ISSUE THREAD

**Issue by praneetha92** [YuSugihara/QTL-seq#12]
Hi @YuSugihara 
I came across this error, i couldn't figure out whether there is a problem while installing the package or some technical issue. Can you please help me out.
![Screenshot from 2020-12-01 19-56-09](https://user-images.githubusercontent.com/72295848/101305832-85a77d80-3869-11eb-921e-2efb0ccedc68.png)

**Comment by YuSugihara** [comment]
Can you see the qtlseq_bam_fainal/40_qtlseq/snp_index.tsv.temp from the directory where you executed QTL-seq?
Error message mentioned it.

You can restart the final stage calculating SNP-index by qtlplot command.
If you will fail the command at the same point, please share the resulting files if possible.
I will figure out your problem.

**Comment by praneetha92** [comment]
Hi @YuSugihara 
The file folder which is created for 40_qtlseq is empty, i tried qtlplot command using the vcf files, there are two files in the vcf directory namely qtlseq.vcf.gz and qtlseq.vcf.gz.tbi, i used the latter one. This is the output.
![Screenshot from 2020-12-07 16-06-37](https://user-images.githubusercontent.com/72295848/101341629-616a9180-38a7-11eb-81f7-364cb64dcf9a.png)

**Comment by praneetha92** [comment]
Hi @YuSugihara 
I used qtlseq.vcf.gz file and i ended up having the error which i mentioned in my first comment.

**Comment by YuSugihara** [comment]
How about BAM files in 20_bams?
Maybe, the sequence reads were too thin.

**Comment by praneetha92** [comment]
Hi @YuSugihara 
The sizes of bam files are as follows 
1. bulk1.filt - 3.6 GB
2. bulk2.filt - 1.2 GB
3. parent.filt - 712 bytes
I made sure that bulk1 and bulk 2 are different but i couldn't solve the error, can you please tell me whether the format(i.e uncompressed or gz format) of the fastq matter while creating the Bam file?

**Comment by YuSugihara** [comment]
The BAM file of the parental cultivar is too small.
I guess it is the causal problem.

2020年12月11日(金) 20:21 praneetha <notifications@github.com>:

**Comment by praneetha92** [comment]
Hi @YuSugihara 
Can you please tell me if there is anything that i might fix to solve the error?

**Comment by YuSugihara** [comment]
If you input a FASTQ file, please confirm that it has the proper content.
No sequence reads cannot produce the result.

If you directly input the BAM file, your alignment fails.

**Comment by praneetha92** [comment]
Hi @YuSugihara 
In the test dataset can you please tell me from where did you consider taking the parent's(nortai and hitomebore) fastq sequence

**Comment by YuSugihara** [comment]
Sorry, I could not understand what you mean.
If you want to try the test dataset, you can copy and paste the lines in 'qtlseq.sh'.

**Comment by praneetha92** [comment]
Hi @YuSugihara 
can you please tell me whether you downloaded the parent's fastq from NCBI?

**Comment by YuSugihara** [comment]
Fastq files for the test dataset are stored in the directory of 'test' on Github.
Do you want to download the full Fastq?

**Comment by praneetha92** [comment]
Hi @YuSugihara 
Yes i want to download full fastq

**Comment by YuSugihara** [comment]
Ok.
If you want to try full fastq files, please check our preprints.
You can google the IDs described in the caption of Fig. 1.
https://www.biorxiv.org/content/10.1101/2020.06.28.176586v1.full.pdf

They are deposited on DRAsearch.
