### ISSUE TITLE
Query on the parent sequence input

### ISSUE THREAD

**Issue by gokulan-15** [YuSugihara/QTL-seq#13]
Hi, @YuSugihara! 

I would like to be clarified on which sequence to input for the `--parent` option in QTL-seq - Is it the parent that shows the desired phenotype or the one that does not? 

Similarly, what should be the input for `--cultivar` in MutMap: wildtype or the mutant sequence? Your reply to these would be of great help.

Best!
Gokulan.

**Comment by YuSugihara** [comment]
In detail, please look at the original QTL-seq papaer by Takagi et al. (2013).

'--parent' option in QTL-seq is to input a sequence file for either of the parents used to create bulked populations. 
'--cultivar' option in MutMap is to input a sequence file for NOT mutagenized parent to create bulked populations.

These options are used to polarize the bulked alleles.

**Comment by gokulan-15** [comment]
Thanks for the clarification, @YuSugihara!
