### ISSUE TITLE
ERROR IN running SnpEff

### ISSUE THREAD

**Issue by Vamshi02** [YuSugihara/QTL-seq#15]
The code which I have given to run qtlplot with the VCF file:  qtlplot -v 30_vcf/qtlseq.vcf -o qtlseq_2.2 -n1 15 -n2 15 -w 1000 -s 500 -S 3 -e Cicer

[QTL-seq:2021-01-18 15:05:23] start to run QTL-plot.
[QTL-seq:2021-01-18 15:05:23] maximum number of threads which you can use is up to 8.
[QTL-seq:2021-01-18 15:05:23] start to run SnpEff.
Traceback (most recent call last):
  File "/home/vamshi/miniconda3/bin/qtlplot", line 33, in <module>
    sys.exit(load_entry_point('qtlseq', 'console_scripts', 'qtlplot')())
  File "/home/vamshi/Downloads/qtlseq/QTL-seq/qtlseq/qtlplot.py", line 207, in main
    qp.run()
  File "/home/vamshi/Downloads/qtlseq/QTL-seq/qtlseq/qtlplot.py", line 189, in run
    self.run_snpEff()
  File "/home/vamshi/Downloads/qtlseq/QTL-seq/qtlseq/qtlplot.py", line 46, in run_snpEff
    sbp.run(cmd, stdout=sbp.DEVNULL, stderr=sbp.DEVNULL, shell=True, check=True)
  File "/home/vamshi/miniconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'snpEff ann -s qtlseq_2.2/snpEff_summary.html SnpEff 30_vcf/qtlseq.vcf 1> qtlseq_2.2/qtlseq.snpEff.vcf 2> qtlseq_2.2/snpEff.log' returned non-zero exit status 255.

It would be great if I had some help solving this issue.
Thanks in advance.

**Comment by YuSugihara** [comment]
Sorry for my poor documents for SnpEff.
I would like to add the documents for SnpEff as soon as possible....

Anyway, did you check the correct name in the SnpEff database?
You can check the database via SnpEff command (in detail, please refer the manual for SnpEff).

**Comment by Vamshi02** [comment]
Yes, I have created a database in SnpEff of cicer aretenium genome. when I checked in the database, I can find my genome. when I run it the error was the same. Please do let me know If I am missing anything. Thank you for your response.

**Comment by sangeeta10mar** [comment]
Please tell how you have created snpEff database for cicer.

**Comment by YuSugihara** [comment]
Please check the README in this repository: https://github.com/YuSugihara/QTL-seq#Built-and-use-your-own-database-for-snpEff

Also, please check the original document in snpEff.

Once you created the database for snpEff, you just specify the name of the database using the '-e' option.
