### ISSUE TITLE
How to use this with two parent and two bulk?

### ISSUE THREAD

**Issue by haohui123** [YuSugihara/QTL-seq#18]
**How to use this with two parent and two bulk?** 
Thanks you for your code supply for us!
The guide tell us just use a single whole-genome resequencing of either of the parental cultivars. if so, whether the accury of result maybe lower than use two parent?  
If use two parents, how can I use your code?

**Comment by hannyxie** [comment]
you can filtered before input，or just use one parent，in most case one/two parents will get similar result.Or use other pipeline.         
            
                
                    
                            
                                
                            
                            
                                解涵
                            
                    
                        
                            
                                    邮箱：18326667320@163.com
                            
                        
                
            
        On 02/22/2021 09:17, haohui123 wrote: 
How to use this with two parent and two bulk?
Thanks you for your code supply for us!
The guide tell us just use a single whole-genome resequencing of either of the parental cultivars. if so, whether the accury of result maybe lower than use two parent?
If use two parents, how can I use your code?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/YuSugihara/QTL-seq/issues/18",
"url": "https://github.com/YuSugihara/QTL-seq/issues/18",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by haohui123** [comment]
Thanks you！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuSugihara/QTL-seq"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 上午9:30
收件人:&nbsp;"YuSugihara/QTL-seq"<QTL-seq@noreply.github.com&gt;;
抄送:&nbsp;"杨好慧"<475889337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YuSugihara/QTL-seq] How to use this with two parent and two bulk? (#18)





 you can filtered before input，or just use one parent，in most case one/two parents will get similar result.Or use other pipeline.         
             
                 
                     
                             
                                 
                             
                             
                                 解涵
                             
                     
                         
                             
                                     邮箱：18326667320@163.com
                             
                         
                 
             
         On 02/22/2021 09:17, haohui123 wrote: 
 How to use this with two parent and two bulk?
 Thanks you for your code supply for us!
 The guide tell us just use a single whole-genome resequencing of either of the parental cultivars. if so, whether the accury of result maybe lower than use two parent?
 If use two parents, how can I use your code?
 
 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 [
 {
 "@context": "http://schema.org",
 "@type": "EmailMessage",
 "potentialAction": {
 "@type": "ViewAction",
 "target": "https://github.com/YuSugihara/QTL-seq/issues/18",
 "url": "https://github.com/YuSugihara/QTL-seq/issues/18",
 "name": "View Issue"
 },
 "description": "View this Issue on GitHub",
 "publisher": {
 "@type": "Organization",
 "name": "GitHub",
 "url": "https://github.com"
 }
 }
 ] 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by YuSugihara** [comment]
Basically, the results should be same in both parental cultivar.
However, maybe SNPs which can be used will be different if the input parental cultivar has many missing than another one. 
If you consider both sequences of parental cultivar, you can run QTL-seq twice.

**Comment by gplee85** [comment]
> Basically, the results should be same in both parental cultivar.
> However, maybe SNPs which can be used will be different if the input parental cultivar has many missing than another one.
> If you want to consider the sequences of both parental cultivars, you can run QTL-seq twice.

Can I input a F1 cultivar for the parental cultivar, or merged bam of P1 and P2 instead of using either one?

**Comment by YuSugihara** [comment]
I do NOT recommend, but you can try.

**Comment by xiekunwhy** [comment]
Hi,

You can try https://github.com/xiekunwhy/bsa
Best,
Kun
