### ISSUE TITLE
!!ERROR!! trimmomatic PE -threads 2 -phred33, how to soloution?

### ISSUE THREAD

**Issue by haohui123** [YuSugihara/QTL-seq#19]
qtlseq -r R_genome.fasta -p QT4Rparent1.clean.fq.gz,QT4Rparent2.clean.fq.gz -b1 QT4Rpool1.clean.fq.gz,QT4Rpool2.clean.fq.gz -b2 QT4Spool1.clean.fq.gz,QT4Spool2.clean.fq.gz -n1 30 -n2 30 -o QT4new-dir -T
occur error as follows:
!!ERROR!! trimmomatic PE -threads 2 -phred33 QT4Rparent1.clean.fq.gz QT4Rparent2.clean.fq.gz QT4new-dir/00_fastq/parent.0000.1.trim.fastq.gz QT4new-dir/00_fastq/parent.0000.1.unpaired.fastq.gz QT4new-dir/00_fastq/parent.0000.2.trim.fastq.gz QT4new-dir/00_fastq/parent.0000.2.unpaired.fastq.gz LEADING:20 TRAILING:20 SLIDINGWINDOW:4:15 MINLEN:75 >> QT4new-dir/log/trimmomatic.log 2>&1

**Comment by YuSugihara** [comment]
Please check the log file "QT4new-dir/log/trimmomatic.log 2>&1"
If it is empty or nothing, please run QTL-seq again.
If you will face the same error, please try the test dataset which is put the Github page.
