### ISSUE TITLE
[W::bam_merge_core2] No @HD tag found

### ISSUE THREAD

**Issue by InfoSuresh** [YuSugihara/QTL-seq#2]
It's giving notification.
 [W::bam_merge_core2] No @HD tag found error. 
Program terminated after generating BAM file.
I enclosed the log file.
[bwa.log](https://github.com/YuSugihara/QTL-seq/files/4341541/bwa.log)
[trimmomatic.log](https://github.com/YuSugihara/QTL-seq/files/4341542/trimmomatic.log)
[samtools.log](https://github.com/YuSugihara/QTL-seq/files/4336147/samtools.log)

**Comment by YuSugihara** [comment]
Sorry for my late reply.
We attached the test dataset on the main Github page.
Please check whether your dataset has a problem or not using that test dataset.
