### ISSUE TITLE
No smooth SNP-index line in the "bulk1_SNPindex.png,bulk2_SNPindex.png and delta_SNPindex.png"

### ISSUE THREAD

**Issue by jigaoxiang** [YuSugihara/QTL-seq#27]
Dear doctor:
         Thanks for your outstanding for this QTL-seq tool. But some question appear when I use the qtlseq software. When I use the test data to perform  below code:
```
qtlseq -o test -n1 20 -n2 20  -w 100 -s 20 -r qtlseq_ref.fasta -p qtlseq_parent.1.fastq.gz,qtlseq_parent.2.fastq.gz \
 -b1 qtlseq_bulk1.1.fastq.gz,qtlseq_bulk1.2.fastq.gz \
 -b2 qtlseq_bulk2.1.fastq.gz,qtlseq_bulk2.2.fastq.gz
```
And then, there are not warring and error happing, like this
```
[QTL-seq:2022-01-11 11:33:45] start to run QTL-seq.
[QTL-seq:2022-01-11 11:33:45] maximum number of threads which you can use is up to 160.
[QTL-seq:2022-01-11 11:33:45] start to index reference fasta.
[QTL-seq:2022-01-11 11:33:46] indexing of reference successfully finished.
[QTL-seq:2022-01-11 11:33:46] start to align reads of parent.0000 by BWA.
[QTL-seq:2022-01-11 11:33:52] alignment parent.0000 successfully finished.
[QTL-seq:2022-01-11 11:33:52] start to align reads of bulk1.0000 by BWA.
[QTL-seq:2022-01-11 11:33:58] alignment bulk1.0000 successfully finished.
[QTL-seq:2022-01-11 11:33:58] start to align reads of bulk2.0000 by BWA.
[QTL-seq:2022-01-11 11:34:04] alignment bulk2.0000 successfully finished.
[QTL-seq:2022-01-11 11:34:04] start to merge BAMs.
[QTL-seq:2022-01-11 11:34:06] merging process successfully finished.
[QTL-seq:2022-01-11 11:34:06] start to call variants.
[QTL-seq:2022-01-11 11:34:31] variant calling successfully finished.
[QTL-seq:2022-01-11 11:34:31] start to index VCF.
[QTL-seq:2022-01-11 11:34:31] indexing VCF successfully finished.
[QTL-seq:2022-01-11 11:34:32] start to run QTL-plot.
[QTL-seq:2022-01-11 11:34:32] maximum number of threads which you can use is up to 160.
[QTL-seq:2022-01-11 11:34:32] start to calculate SNP-index.
[QTL-seq:2022-01-11 11:34:53] SNP-index successfully finished.
[QTL-seq:2022-01-11 11:34:53] start to smooth SNP-index.
[QTL-seq:2022-01-11 11:34:53] smoothing process successfully finished.
[QTL-seq:2022-01-11 11:34:53] plotting now...
[QTL-seq:2022-01-11 11:34:54] QTL-plot successfully finished.
[QTL-seq:2022-01-11 11:34:54] QTL-seq successfully finished.
```
However, When I check the figure in 40_qtlseq file, there are no smooth lines in "bulk1_SNPindex.png,bulk2_SNPindex.png and delta_SNPindex.png", as the example follow show:
![bulk1_SNPindex (2)](https://user-images.githubusercontent.com/65279501/148881531-5f6fc65e-d01e-41b7-994e-ebde9a03fd89.png)
![delta_SNPindex (2)](https://user-images.githubusercontent.com/65279501/148882172-67d6e402-94ca-4a9f-9440-a8d4a27863a1.png)

Could you give some advice for that? Thanks again for your help!

Best regards,
Gaoxiang Ji

**Comment by YuSugihara** [comment]
This is strange.
Would you check the resulting files?
How are the p95 and p99 thresholds described in them?

**Comment by jigaoxiang** [comment]
> This is strange. Would you check the resulting files? How are the p95 and p99 thresholds described in them?
Dear doctor:        
            Thank you for your reply! I checked the resulting files. there are no problems with the p95 and p99. And then, I tried our own data using qtl-seq tool,  the smooth lines appeared surprisingly! So, I did not pay more time in the test data! Thank you again for this useful tool!   

Best wish!,
Gaoxiang Ji

**Comment by Shenu-Hudson** [comment]
I'm facing the same issue, In the image the p95 and p99 and mean markings are missing. Could you please look into the attached files?


![delta_SNPindex](https://user-images.githubusercontent.com/105225514/207043294-2b5ae27d-144a-4b90-a729-3ede9b83c936.png)
. 
![image](https://user-images.githubusercontent.com/105225514/207043747-afc36dc5-476e-4c8a-a06c-29c499ccbec6.png)

**Comment by Rkbiotech0709** [comment]
I am also facing the same issue.

![image](https://github.com/YuSugihara/QTL-seq/assets/146990014/6ce8b8ab-aab4-4b4f-afca-e294be5d2293)

**Comment by YuSugihara** [comment]
Hi,
I can see both p95 and p99 lines, which are green and yellow, respectively.
So, it seems to be working nicely for me.
Sometimes, the lines are broken because there are no mutations on the locus and the program could not calculate sliding window.
How about the peak in LG04?

Best regards,
Yu

**Comment by YuSugihara** [comment]
> > This is strange. Would you check the resulting files? How are the p95 and p99 thresholds described in them?
> > Dear doctor:
> > Thank you for your reply! I checked the resulting files. there are no problems with the p95 and p99. And then, I tried our own data using qtl-seq tool,  the smooth lines appeared surprisingly! So, I did not pay more time in the test data! Thank you again for this useful tool!
> 
> Best wish!, Gaoxiang Ji

Just to leave some information for future users:
The default window size (2Mbp) is optimized for rice genome based on our experience.
However, sometimes this is too large for small contigs or test datasets.
When the contig is size is smaller than 2Mbp and you ran QTL-seq with default window size, you might not see the smoothing lines.

Yu
