### ISSUE TITLE
Citation of Huang et al. (2019)

### ISSUE THREAD

**Issue by dinosaurur** [YuSugihara/QTL-seq#3]
Hi!
May I have the full citation of Huang et al. (2019)?
I am curious about how the equation of the value 'k' was decided and affects the threshold.
Thank you very much!

**Comment by YuSugihara** [comment]
Sorry for my late response.

Currently, you can specify it from the species name.
However, if you want to use Huang's method, we highly recommend you to use their original method.

About this problem, please contact me, directly.

yu57th<a>gmail.com
