### ISSUE TITLE
Error with snpEff

### ISSUE THREAD

**Issue by SowmyaPulapet** [YuSugihara/QTL-seq#35]
Hello,
       I am stuck at the part where snpEff has to be used because the snpEff version downloaded along with qtlseq is version 5.12, made with java 12. The conda does not have java 12 package yet. How can I use snpEff for qtlseq then? Please help me.

**Comment by YuSugihara** [comment]
I'm sorry for the late response.

Our conda protocol does not request any versions of JAVA, which means that either SnpEff or trimmomatic requried that version of JAVA or that your other software require it.

Maybe, to avoid the conflict of java version, you can create a new QTL-seq environemnt with:
``` bash
conda create -c bioconda -n qtlseq qtlseq
conda activate qtlseq
``` 
 
Also, we added the supplementary document for how to use snpEff:
https://github.com/YuSugihara/QTL-seq/blob/master/docs/02_Guide_to_Build_SnpEff_DB.md

I hope this document is helpful.

Yu
