### ISSUE TITLE
Regarding visualization of INDELs with delta-SNP-index of 1

### ISSUE THREAD

**Issue by minh-liem** [YuSugihara/QTL-seq#36]
Hello.
I'm new to bioinformatics and I have some questions regarding QTL-seq as I'm experimenting this method. 

I detected some INDELS with delta-SNP-index of 1. However, as I try to visualize them using IGV, they seem to be off-target (usually some bases to the right). Here in the picture I have an INDEL that was supposed to be ..67-..68, yet the deletion seems to be in ..69 position. Furthermore, bases in the parent and the two progeny bulks are identical, which was not what I expected (accordingly, the low phenotype should contain only A but most of their reads still have G after that). 

Did I do anything incorrectly?  

![ques](https://user-images.githubusercontent.com/105168274/181481649-e844e8c5-b7c4-4883-b170-e8b3c22d98a2.png)

**Comment by YuSugihara** [comment]
I'm not sure if I answer that you want to know, but I can see the deletion at "G" in low phenotype.
I guess that your VCF says that "AG" is in high phenotype and "A" is in low phenotype, which means the deletion of "G".
Please check other sequence read in low phenotype, scrolling down the IGV.
