### ISSUE TITLE
QTL-seq produced unusual BAM file 

### ISSUE THREAD

**Issue by mhw05727** [YuSugihara/QTL-seq#37]
Hi, 
I'm working with QTL-seq pipeline and have successfully finished the analysis using parent 1. However, when I tried to redo the analysis using parent 2, it always stopped in the delta SNP calculation step. After I investigate, there might be an issue with BAM file for parent 2 which is too small and not reasonable. I have tried to use a new copy of the fastq file of parent 2 but still results in the same error. 
Could anyone help me with this? 

Thanks!

**Comment by YuSugihara** [comment]
I'm sorry for the late response.

I leave some comments for future QTL-seq users.

When you report the error, please provide both the script that you used and the error message.
Without the detail error message, I cannot comments on how to solve the error.

I suspect that your parent 2 has too heterogeneous genome.
QTL-seq uses the parental bam file to filter our the SNPs in the VCF file.
If your parental bam has too many heterogeneous markers, all the SNPs are filtered out.

Yu
