### ISSUE TITLE
Error for samtools error info

### ISSUE THREAD

**Issue by Chuhao-Li** [YuSugihara/QTL-seq#38]
Dear developer, 

The Samtools error information as following stops the pipeline. I think it's not really an error. 

[QTL-seq:2022-12-06 10:14:05] start to merge BAMs.
[QTL-seq:2022-12-06 10:52:35] !!ERROR!! samtools sort -m 1G -@ 40 -o 008qtlseq/qtlseq_out/20_bam/bulk1.bam 008qtlseq/qtlseq_out/20_bam/bulk1.unsorted.bam >> 008qtlseq/qtlseq_out/log/samtools.log 2>&1

**Comment by YuSugihara** [comment]
I'm sorry for the late response.

I leave some comments for future QTL-seq users.

When QTL-seq stops an error, please refer to the message on the terminal or in the log file.
In this case, `008qtlseq/qtlseq_out/log/samtools.log` might have the information to solve the error.
