### ISSUE TITLE
During alignment Im encountering a error [main_samview] fail to read the header from "-".

### ISSUE THREAD

**Issue by shashidhar111** [YuSugihara/QTL-seq#41]
After running the code 

qtlseq --ref GCF_000741045.1_Vradiata_ver6_genomic.fna --parent parent.0000.1.trim.fastq,parent.0000.2.trim.fastq --bulk1 output_R1_paired.fq,output_R2_paired.fq --bulk2 output_S1_paired.fq,output_S2_paired.fq --N-bulk1 20 --N-bulk2 20 --out results1 --filial 8 --threads 20

[QTL-seq:2023-03-02 21:25:16] start to run QTL-seq.
[QTL-seq:2023-03-02 21:25:16] maximum number of threads which you can use is up to 20.
!!WARNING!! You can use up to 20 threads. This program will use 20 threads.
[QTL-seq:2023-03-02 21:25:16] start to index reference fasta.
[QTL-seq:2023-03-02 21:32:59] indexing of reference successfully finished.
[QTL-seq:2023-03-02 21:32:59] start to align reads of parent.0000 by BWA.

[QTL-seq:2023-03-02 21:34:03] !!ERROR!! bwa mem -t 20 results1/10_ref/GCF_000741045.1_Vradiata_ver6_genomic.fna parent.0000.1.trim.fastq parent.0000.2.trim.fastq | samtools fixmate -m - - | samtools sort -m 1G -@ 20 | samtools markdup -r - - | samtools view -b -f 2 -F 2048 -o results1/20_bam/parent.0000.bam >> results1/log/alignment.log 2>&1

please check below:

[main_samview] fail to read the header from "-".

**Comment by shashidhar111** [comment]
[main_samview] fail to read the header from "-".

**Comment by shashidhar111** [comment]
Same error with the test file

qtlseq --ref qtlseq_ref.fasta --parent qtlseq_parent.1.fastq.gz,qtlseq_parent.2.fastq.gz --bulk1 qtlseq_bulk1.1.fastq.gz,qtlseq_bulk1.2.fastq.gz --bulk2 qtlseq_bulk2.1.fastq.gz,qtlseq_bulk2.2.fastq.gz --N-bulk1 20 --N-bulk2 20 --out results --filial 8 --threads 20


[QTL-seq:2023-03-02 21:44:32] start to run QTL-seq.
[QTL-seq:2023-03-02 21:44:32] maximum number of threads which you can use is up to 20.
!!WARNING!! You can use up to 20 threads. This program will use 20 threads.
[QTL-seq:2023-03-02 21:44:32] start to index reference fasta.
[QTL-seq:2023-03-02 21:44:33] indexing of reference successfully finished.
[QTL-seq:2023-03-02 21:44:33] start to align reads of parent.0000 by BWA.
[QTL-seq:2023-03-02 21:44:36] !!ERROR!! bwa mem -t 20 results/10_ref/qtlseq_ref.fasta qtlseq_parent.1.fastq.gz qtlseq_parent.2.fastq.gz | samtools fixmate -m - - | samtools sort -m 1G -@ 20 | samtools markdup -r - - | samtools view -b -f 2 -F 2048 -o results/20_bam/parent.0000.bam >> results/log/alignment.log 2>&1

please check below:

[main_samview] fail to read the header from "-".

**Comment by YuSugihara** [comment]
Sorry for my late reply.
Which samtools version are you using?

This is potentially because of too old samtools version.
Would you please try to update your samtools?

Best regards,
Yu

**Comment by shashidhar111** [comment]
Thanks for the reply, I solved the problem by reducing the number of
threads. At first I had assigned all my 20 then I reduced, worked perfectly.
Thank you

**Comment by YuSugihara** [comment]
That's nice!

Thank you very much for reporting the error.
These comments are definitely helpful for future users.

Again, I'm sorry for my late response.

Best regards,
Yu
