### ISSUE TITLE
Raw data for plotting with ggplot

### ISSUE THREAD

**Issue by caiobrunharo** [YuSugihara/QTL-seq#42]
Hi. 

The output of my run results in a single file with many plots with the same x-axis. I would like to use the raw data to plot myself using ggplot2 so that I can manipulate the axis, highlight datapoints, etc. How can I obtain the raw data that was used to generate the outputs in directory 40_qtlseq?

Thanks!

**Comment by YuSugihara** [comment]
Yes, you can.
Please check the  README: https://github.com/YuSugihara/QTL-seq#outputs

Best,
Yu
