### ISSUE TITLE
qtlseq qtl-seq error occur 

### ISSUE THREAD

**Issue by HaNjIhEoN1** [YuSugihara/QTL-seq#45]
hello I have a question about some error

I downloaded the test file and ran it in the way of example 2.

qtlseq -r reference.fasta
     -p parent.1.fastq,parent.2.fastq
     -b1 bulk_1.1.fastq,bulk_1.2.fastq
     -b2 bulk_2.1.fastq,bulk_2.2.fastq
     -n1 20
     -n2 20
     -o example_dir
     -T

[QTL-seq:2023-09-18 15:04:12] start to run QTL-seq.
[QTL-seq:2023-09-18 15:04:12] maximum number of threads which you can use is up to 8.
Traceback (most recent call last):
  File "/home/jjw/miniconda3/envs/qtl/bin/qtlseq", line 33, in <module>
    sys.exit(load_entry_point('qtlseq', 'console_scripts', 'qtlseq')())
  File "/home/jjw/QTL-seq/qtlseq/qtlseq.py", line 173, in main
    QTLseq(args).run()
  File "/home/jjw/QTL-seq/qtlseq/qtlseq.py", line 36, in __init__
    self.link_ref()
  File "/home/jjw/QTL-seq/qtlseq/qtlseq.py", line 63, in link_ref
    os.symlink(path_to_ref, sym_ref)
OSError: [Errno 38] Function not implemented: '/media/jjw/seagate/hy/fasta/qtlseq_ref.fasta' -> 'test/10_ref/qtlseq_ref.fasta'

However, an error occurred. The error contents are as follows.

OSError: [Errno 38] Function not implemented: 'qtlseq_ref.fasta' -> 'example/10_ref/qtlseq_ref.fasta'

Please tell me the solution or the cause of the problem

**Comment by YuSugihara** [comment]
Thank you very much for reporting the error.

I have never seen this kind of error before.

This looks that your OS does not have symbolic command "ln".

 I have recently prepared [the document](https://github.com/YuSugihara/QTL-seq/blob/master/docs/01_QTL-seq_Commands_Breakdown.md) to describe the commands in QTL-seq and this error looks relevant to [this section](https://github.com/YuSugihara/QTL-seq/blob/master/docs/01_QTL-seq_Commands_Breakdown.md#step-3-reference-genome-indexing).

I hope this document is helpful.

Yu
