### ISSUE TITLE
can you help me ?

### ISSUE THREAD

**Issue by liuxiaowei0401** [YuSugihara/QTL-seq#5]
Hi, I think it's a good package. But I had a problem. Because I use VCF in different formats, I can't use these packages. I only need to use these packages to calculate CI. Can you give me a method to calculate 99% and 95% CI only according to reads depth.

**Comment by YuSugihara** [comment]
Hello and sorry for my late response.
Currently, you have to use the proper format of VCF.

If you cannot prepare it by your script, 
the easiest way is to use our pipeline from the initial point.

Best regards
