### ISSUE TITLE
Program Killed

### ISSUE THREAD

**Issue by KuldeepKumarSoni** [YuSugihara/QTL-seq#9]
I was working on QTLseq data analysis using YuSugihar/QTL-seq. All process was running smoothly, folder 10_ref, 20_bam, 30_vcf were created. But, suddenly I got an error "PROGRAM KILLED". My queries is inspite of re running the whole program, can I continue it from the same, because is taking much time to make these files.
![Screenshot from 2020-09-08 11-24-31](https://user-images.githubusercontent.com/70935453/92438314-339d8000-f1c6-11ea-8152-8f6a4a7fb1dd.png)

**Comment by YuSugihara** [comment]
Please run again.
I didn't face such an error.
